version = 1

[[analyzers]]
name = "java"

  [analyzers.meta]
  runtime_version = "11"

  [[analyzers]]
  name = "test-coverage"
  enabled = true

  DEEPSOURCE_DSN = "https://62d08ef14dea4340bbe677e05b9f7080@app.deepsource.com"